return {
	{ "block", id="cover" },
	{ "block",
		{ "block", id="menu",
			{ "text",   value="Options",          id="title" },
			{ "button", value="Debug",            id="debug" },
			{ "button", value="Mute",             id="mute" },
			{ "button", value="Hyper Speed",      id="hyper_speed" },
			{ "text",                             id="volume_label" },
			{ "button", value="Master Volume +",  id="volume_up" },
			{ "button", value="Master Volume -",  id="volume_down" },
			{ "text",                             id="bgm_label" },
			{ "button", value="Music Volume +",   id="bgm_volume_up" },
			{ "button", value="Music Volume -",   id="bgm_volume_down" },
			{ "text",                             id="sfx_label" },
			{ "button", value="Effects Volume +", id="sfx_volume_up" },
			{ "button", value="Effects Volume -", id="sfx_volume_down" },
			{ "text",                             id="voice_label" },
			{ "button", value="Voice Volume +",   id="voice_volume_up" },
			{ "button", value="Voice Volume -",   id="voice_volume_down" },
			{ "button", value="Exit",             id="exit" },
		},
	},
}
